#pragma config(Sensor, S1,     UltSou_Sensor,  sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Light_Sensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          Arm_Motor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          Left_motor,    tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right_motor,   tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int basespd = 35;
int fastspd = 34;
int pausetime = 45;


float UltSou_grade;

void beepGreen(){
	setMotorSpeed(Right_motor, 0);
  setMotorSpeed(Left_motor, 0);
	playImmediateTone(2000, 200);
	sleep(500);
	setMotorSpeed(Arm_Motor, -10);
	sleep(1000);

	setMotorSpeed(Right_motor, -20);
	setMotorSpeed(Left_motor, 20);
	sleep(1000);
	setMotorSpeed(Right_motor, 20);
	setMotorSpeed(Left_motor, -20);
	setMotorSpeed(Arm_Motor, 10);
	sleep(1000);
	setMotorSpeed(Arm_Motor, 0);

}

void beepBlue(){
	setMotorSpeed(Right_motor, 0);
  setMotorSpeed(Left_motor, 0);
	playImmediateTone(2000, 200);
	sleep(500);

	setMotorSpeed(Right_motor, 20);
	setMotorSpeed(Left_motor, -25);
	sleep(1000);
}




task main()
{
	int garbage[3];
	getColorRGB(Light_Sensor, garbage[0], garbage[1], garbage[2]);

	//calibration
	int greenCalibration[3];
	int blueCalibration[3];
	int offlineCalibration[3];

	displayTextLine(1, "green");
	delay(4000);
	getColorRGB(Light_Sensor, greenCalibration[0], greenCalibration[1], greenCalibration[2]);
	displayTextLine(1, "              ");


	displayTextLine(1, "blue");
	delay(4000);
	getColorRGB(Light_Sensor, blueCalibration[0], blueCalibration[1], blueCalibration[2]);
	displayTextLine(1, "              ");

	displayTextLine(1, "offline");
	delay(4000);
	getColorRGB(Light_Sensor, offlineCalibration[0], offlineCalibration[1], offlineCalibration[2]);
	displayTextLine(1, "              ");

	displayTextLine(1, "Place Beside Line");
	delay(3000);
	displayTextLine(1, "              ");

	int Left_pos;
	int Right_pos;
//bool t=false;
//setMotorBrakeMode(Left_motor,motorCoast); //The motor will now Coast (does not resist movement)
	setMotorBrakeMode(Left_motor,motorBrake); //The motor will now Hold (resist movement and stay at position)
	setMotorBrakeMode(Right_motor,motorBrake);
	resetMotorEncoder(Left_motor);
	resetMotorEncoder(Right_motor);

	//color mask
	while(true) {


		setMotorSpeed(Left_motor, basespd);
		setMotorSpeed(Right_motor, basespd);

    int red, green, blue;
    getColorRGB(Light_Sensor, red, green, blue);

    if(abs(greenCalibration[0] - red) < 10 && abs(greenCalibration[1] - green) < 10 && abs(greenCalibration[2] - blue) < 10) {
        displayTextLine(2, "green");
        setMotorSpeed(Right_motor, -5);
        setMotorSpeed(Left_motor, fastspd+25);
        sleep(pausetime+50);

        UltSou_grade = getUSDistance(UltSou_Sensor); // Returns the value of the Ultrasonic Distance sensor
				displayStringAt(1,100, "%f",UltSou_grade);
				if(UltSou_grade <= 10){
					beepGreen();
				}

    } else if(abs(blue - blueCalibration[2]) < 10) {
        displayTextLine(2, "blue");
        setMotorSpeed(Right_motor, 0);
        setMotorSpeed(Left_motor, fastspd-10);
        sleep(pausetime);

        UltSou_grade = getUSDistance(UltSou_Sensor); // Returns the value of the Ultrasonic Distance sensor
				displayStringAt(1,100, "%f",UltSou_grade);
				if(UltSou_grade <= 10){
					beepBlue();
				}

    } else if(abs(offlineCalibration[0] - red) < 10 && abs(offlineCalibration[1] - green) < 10 && abs(offlineCalibration[2] - blue) < 10) {
        displayTextLine(2, "off line");
        setMotorSpeed(Right_motor, fastspd-5);
        setMotorSpeed(Left_motor, 0);
        sleep(pausetime);

    } /*else {
        displayTextLine(2, "blue");
        setMotorSpeed(Right_motor, 0);
        setMotorSpeed(Left_motor, fastspd-10);
        sleep(pausetime);

        UltSou_grade = getUSDistance(UltSou_Sensor); // Returns the value of the Ultrasonic Distance sensor
				displayStringAt(1,100, "%f",UltSou_grade);
				if(UltSou_grade <= 10){
					beepBlue();
				}
    }*/
}







}
